#!/bin/sh
#
# rsync-mirror of items that are intended to be public.
#
# An item is intended to be public if it contains any of
# our preferred matches, below, such as "/public/".
#
# Examples:
#
#     foo/public/bar
#     foo-public-bar
#     foo.public.bar
#
# Program: rsync-mirror-public-content
# Version: 3.0.0
# Created: 2015-01-25
# Updated: 2019-08-23
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
rsync -aHuOxzvi \
    --timeout=60 \
    --include '*/' \
    --include '/pub/' \
    --include '.pub.' \
    --include '-pub-' \
    --include '/public/' \
    --include '.public.' \
    --include '-public-' \
    --include '*.pub' \
    --include '*-pub' \
    --include '*.public' \
    --include '*-public' \
    --exclude '*' \
    "$@"
