#!/bin/sh
#
# rsync-mirror scoped to items that are public.
#
# Public is any of these:
#
#   * The path is public if:
#
#     * it contains a separator (slash, dash, or comma)
#     * then `pub` or `public`
#     * then the same separator, or the path ends
#
#   * The file is a fingerprint:
#
#     * file name ends with a separator then `fingerprint` or `fingerprints`
#     * file name is "fingerprint" or "fingerprints"
#
#   * The file is encrypted:
#
#     * file name ends with `.gpg`
#
# Examples:
#
#     foo/public/bar
#     foo-public-bar
#     foo.public.bar
#     foo/pub/bar
#
# Program: rsync-mirror-public-content
# Version: 2.3.0
# Created: 2015-01-25
# Updated: 2019-08-23
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
rsync -aHuOxzvi \
    --timeout=60 \
    --include '*/' \
    --include '/pub/' \
    --include '.pub.' \
    --include '-pub-' \
    --include '/public/' \
    --include '.public.' \
    --include '-public-' \
    --include '*.pub' \
    --include '*-pub' \
    --include '*.public' \
    --include '*-public' \
    --include 'fingerprint' \
    --include 'fingerprint.txt' \
    --include 'fingerprints' \
    --include 'fingerprints.txt' \
    --include '*.fingerprint' \
    --include '*.fingerprint.txt' \
    --include '*-fingerprint' \
    --include '*-fingerprint.txt' \
    --include '*.fingerprints' \
    --include '*.fingerprints.txt' \
    --include '*-fingerprints' \
    --include '*-fingerprints.txt' \
    --include 'ssh-host-key-fingerprints.txt' \
    --include 'ssh-host-keys.txt' \
    --include '*.gpg' \
    --exclude '*' \
    "$@"
