#!/bin/sh
#
# rsync-mirror-exact: rsync-mirror then delete all extraneous items.
#
# Syntax:
#
#     rsync-mirror-exact [syntax is the same as rsync]
#
# Example:
#
#     rsync-mirror-exact ~/foo/ ~/bar/
#
# This script is based on `rsync-mirror` which sets these options:
#
#   -a, --archive           archive mode; same as -rlptgoD (no -H)
#   -H, --hard-links        preserve hard links
#   -O, --omit-dir-times    omit directories when preserving times
#   -x, --one-file-system   don't cross filesystem boundaries
#   -z, --compress          compress file data during the transfer
#   -i, --itemize-changes   output a change-summary for all updates
#
# This script also sets this options:
#
#   --delete-after          receiver deletes after transfer
#
# This script deliberately does not set these options:
#
#   -u, --update            skip files that are newer on the receiver
#   -v, --verbose           increase verbosity
#   --partial               keep partially transferred files
#   --progress              show progress during transfer
#   --copy-links            transform symlink into referent file/dir
#   --safe-links            ignore symlinks that point outside the tree
#
# Reasons:
#
#   * We like --hard-links even though this is an expensive calculation.
#   * We only use --omit-dir-times because dir times fail on some systems.
#   * We do not use --partial because temp dirs fail on some systems.
#   * We want symlinks as-is, thus no --safe-links, --copy-links, etc.
#   * We use --delete-after, rather than --delete-before or --delete-during,
#     because we want the command to be able to copy on top of existing items
#     that may link to each other, such as a website that has many pages.
#
# Program: rsync-mirror-exact
# Version: 2.1.0
# Created: 2015-01-25
# Updated: 2019-08-23
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
rsync --timeout=60 -aHuOxzvi --delete-after "$@"
