#!/bin/sh
#
# rsync-mirror of items that are intended to be public.
#
# An item is intended to be public if it contains any of
# our preferred matches, below, such as "/public/".
#
# The matches are deliberately enumerated, rather than using
# regexp patterns, for compatibility with more rsync versions.
#
# The pattern matching rules are:
#
#    * The delimited text "pub" or "public"
#
#    * The delimiters are "/", ".", "-", "_", "=", "~".
#
#    * The delimiting must be a matching pair, or at the end.
#
# Program: rsync-mirror-public
# Version: 3.0.0
# Created: 2015-01-25
# Updated: 2019-08-23
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
rsync --timeout=60 -aHuOxzvi \
    --include '*/' \
    --include '/pub/' --include '/public/' \
    --include '.pub.' --include '*.pub' --include '.public.' --include '*.public' \
    --include '-pub-' --include '*-pub' --include '-public-' --include '*-public' \
    --include '_pub_' --include '*_pub' --include '_public_' --include '*_public' \
    --include '=pub=' --include '*=pub' --include '=public=' --include '*=public' \
    --include '~pub~' --include '*~pub' --include '~public~' --include '*~public' \
    --exclude '*' \
    "$@"
